apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dkf-dep--cert-manager
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: deploykf-dependencies
    app.kubernetes.io/part-of: "deploykf"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: "https://github.com/inferno-f5labs-ai/inferno.f5labs.ai-infrastructure.git"
    targetRevision: "master"
    path: "argocd/apps/deploykf/manifests/deploykf-dependencies/cert-manager"
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values-overrides.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "cert-manager"
