########################################
## SHARED | deploykf-helpers
########################################
deployKF_helpers:
  deploykf_gateway:
    http_endpoint: "kf.f5labs.ai:8080"
    https_endpoint: "kf.f5labs.ai:8443"
    is_self_signed_cert: true

  kubeflow_pipelines:
    use_embedded_minio: 