apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kf-tools--tensorboards--tensorboard-controller
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: tensorboard-controller
    app.kubernetes.io/component: kubeflow-tools
    app.kubernetes.io/part-of: "deploykf"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: "https://github.com/inferno-f5labs-ai/inferno.f5labs.ai-infrastructure.git"
    targetRevision: "master"
    path: "argocd/apps/deploykf/manifests/kubeflow-tools/tensorboards/tensorboard-controller"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeflow
