apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "deploykf-app-of-apps"
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: deploykf-app-of-apps
    app.kubernetes.io/part-of: "deploykf"
spec:
  project: "deploykf"
  source:
    repoURL: "https://github.com/inferno-f5labs-ai/inferno.f5labs.ai-infrastructure.git"
    targetRevision: "main"
    path: "argocd/argocd-apps/deploykf/argocd"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
