apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "deploykf-app-of-apps"
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: deploykf-app-of-apps
    app.kubernetes.io/part-of: "deploykf"
spec:
  project: "default"
  source:
    repoURL: "https://github.com/inferno-f5labs-ai/inferno.f5labs.ai-infrastructure.git"
    targetRevision: "master"
    path: "argocd/argocd-apps/deploykf/argocd"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
