apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## global namespace must be set due to:
## https://github.com/kubernetes-sigs/kustomize/issues/1301#issuecomment-1308228710
namespace: kubeflow

resources:
  ## upstream
  - upstream/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user

  ## local
  - resources/generate-profile-resources-clusterpolicy.yaml
  - resources/restart-on-pipeline-configmap-update-clusterpolicy.yaml
  - resources/clone-bucket-secret-clusterpolicy.yaml